<project name="FlexCoverageProject" default="test">
    <property name="FLEX_HOME" value="/opt/flex"/>
    <property name="src.dir" value="src"/>
    <property name="test.dir" value="test"/>
    <property name="reports.dir" value="coverage"/>

    <mkdir dir="${reports.dir}"/>

    <taskdef resource="flexTasks.tasks"
             classpath="${FLEX_HOME}/ant/lib/flexTasks.jar"/>

    <target name="test">
        <flexunit workingDir="${basedir}" toDir="${reports.dir}" haltonfailure="true" verbose="true">
            <source dir="${test.dir}"/>
            <coverage enabled="true"/>
        </flexunit>
    </target>
</project>
