sonar.projectKey=9.9_Flex:master
sonar.projectName=9.9_Flex
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=test

sonar.inclusions=**/*.as

sonar.coverageReportPaths=coverage/coverage.xml

sonar.sourceEncoding=UTF-8

sonar.host.url=http://sonar.cybage.com
sonar.login=squ_477d321dc2b5eedc131db2b991290c5684c87d65
